[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "torch",
    "ninja"
]
build-backend = "setuptools.build_meta"

[project]
name = "msnerf"
version="1.0.0"
dependencies = [
    "nerfstudio",
    "tinycudann @ git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch"
]
authors = [
  {email = "3200101345@zju.edu.cn"},
  {name = "Leisen Fang"}
]

[tool.setuptools.packages.find]
include = ["msnerf*"]

[project.entry-points.'nerfstudio.method_configs']
msnerf = 'msnerf.ms_config:MsNeRFMethod'